# application.yml

# 공통 설정
server:
  port: 8080

# 기본 프로파일은 local
spring:
  profiles:
    active: local
    
# local 프로파일
---
spring:
  config:
    activate:
      on-profile: local

vcs:
  gitlab:
    url: https://gitlab.iacops.site/gitlab-instance-d4e213ae/iacops-project.git
    username: root  
    password: new1234!
    localpath: /Users/kimjihun/Documents/git/iacops-project/
    strmasterref: refs/remotes/origin/master

ansible:
  playbook_path: /Users/kimjihun/Documents/ansible/playbook/

filePath:
  base: /Users/kimjihun/Documents/git/iacops-project/
  infra_code:
    infra_config: 
      path: ${filePath.base}terraform/
      inventory_infofile: Terraform.tfstate
    sw_config:
      path: ${filePath.base}ansible/

  
# dev 프로파일
---
spring:
  config:
    activate:
      on-profile: dev

vcs:
  gitlab:
    url: https://gitlab.iacops.site/gitlab-instance-d4e213ae/Monitoring.git
    username: root  
    password: new1234!
    localpath: /var/lib/iacops/iacops-project/
    strmasterref: refs/remotes/origin/master

ansible:
  playbook_path: /home/centos/iacops-project/

filePath:
  base: /var/lib/iacops/iacops-project/
  infra_code:
    infra_config: 
      path: ${filePath.base}terraform/
      inventory_infofile: Terraform.tfstate
    sw_config:
      path: ${filePath.base}ansible/
