# application.yml

# 공통 설정
server:
  port: 8080

# 기본 프로파일은 local
spring:
  profiles:
    active: local
    
# local 프로파일
---
spring:
  profiles: local

vcs:
  gitlab:
    url: https://gitlab.iacops.site/gitlab-instance-d4e213ae/Monitoring.git
    username: root  
    password: new1234!
    localpath: /Users/seungmi/Desktop/Monitoring
    strmasterref: refs/remotes/origin/master

ansible:
  playbook_path: /Users/kimjihun/Documents/ansible/playbook/

filePath:
  base: /Users/kimjihun/Documents/git/iacops-project-main/
  infra_code:
    infra_config: 
      path: ${filePath.base}terraform/
      inventory_infofile: Terraform.tfstate
    sw_config:
      path: ${filePath.base}ansible/

  
# dev 프로파일
---
spring:
  profiles: dev

vcs:
  gitlab:
    url: https://gitlab.iacops.site/gitlab-instance-d4e213ae/Monitoring.git
    username: root  
    password: new1234!
    localpath: /Users/seungmi/Desktop/Monitoring
    strmasterref: refs/remotes/origin/master

ansible:
  playbook_path: /home/centos/iacops-project/

filePath:
  base: /home/centos/iacops-project/
  infra_code:
    infra_config: 
      path: ${filePath.base}terraform/
      inventory_infofile: Terraform.tfstate
    sw_config:
      path: ${filePath.base}ansible/


# prod 프로파일
---
spring:
  profiles: prod
  
git:
  url: jdbc:mysql://localhost:3306/proddb
  username: produser
  password: prodpass
