name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SSH Connection Test
        run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
         chmod 600 id_rsa.pem
         ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem -T ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}
         rm id_rsa.pem

#       - name: Deploy and Run
#         run: |
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
#          chmod 600 id_rsa.pem
#          scp -o StrictHostKeyChecking=no -i id_rsa.pem -r ./target/*.jar ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.DEPLOY_DIR }}/app.jar
#          ssh -o StrictHostKeyChecking=no -i id_rsa.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "pkill -f 'java -jar' || true"
#          ssh -o StrictHostKeyChecking=no -i id_rsa.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "nohup java -jar -Dspring.profiles.active=dev ${{ secrets.DEPLOY_DIR }}/app.jar &"
#          rm id_rsa.pem
