name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SSH Connection Test
        run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
         chmod 600 id_rsa.pem
         ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem -T ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}
         rm id_rsa.pem
      - name: Deploy and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
            echo "test" > test.txt            
            chmod 600 id_rsa.pem
            scp -o StrictHostKeyChecking=no -i id_rsa.pem -r ./test.txt .:${{ secrets.DEPLOY_DIR }}/test.txt
