name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SSH Connection Test
        run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
         chmod 600 id_rsa.pem
         ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem -T ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}
         rm id_rsa.pem
      - name: Deploy and Run
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa.pem
          chmod 600 id_rsa.pem
          echo "Starting scp command"
          scp -v -o StrictHostKeyChecking=no -i id_rsa.pem -r ./target/*.jar ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:${{ secrets.DEPLOY_DIR }}/app.jar
          echo "Finished scp command"
          echo "Executing kill command on remote server"
          ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "pkill -f 'java -jar' || true"
          echo "Starting application on remote server"
          ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "nohup java -jar -Dspring.profiles.active=dev ${{ secrets.DEPLOY_DIR }}/app.jar > ${{ secrets.DEPLOY_DIR }}/app.log 2>&1 &"
          echo "Checking application process on remote server"
          ssh -v -o StrictHostKeyChecking=no -i id_rsa.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "pgrep -fl 'java -jar'"
          rm id_rsa.pem
